### ISSUE TITLE
Update CKEditor to 4.5.x

### ISSUE THREAD

**Issue by johanjanssens** [joomlatools/joomlatools-framework-ckeditor#11]
See: http://ckeditor.com/blog/CKEditor-4.5-Released

This release improves browser compatibility. More info see: http://docs.ckeditor.com/#!/guide/dev_browsers

Further references: http://docs.ckeditor.com/#!/guide/dev_unsupported_environments

**Comment by yiendos** [comment]
@jebbdomingo Top Draw! Integrating this updated editor with textman shows a good coverage of android devices now:
- Nexus 6 (droid 6)
- Nexus 5 (droid 4.4) 
- Nexus 7 (droid 4.4) 

Nexus 4 (droid 4.2) couldn't load, but I'm guessing this is a well old version. 

Samsung worked well from Note 4 up to Galaxy 7

Did notice we are rocking an older version of ckeditor here: 
https://github.com/joomlatools/joomlatools-framework-ckeditor/tree/feature/11-ckeditor-4.5/resources/assets

This should be dropped before launching. Good work sir
