### ISSUE TITLE
Errors when CKEditor and TinyMCE are used in a Page

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework-ckeditor#2]
The toolbar buttons are not working when there's both TinyMCE and CKEditor on the page

method = this[method] ? method : '_actionDefault';
this[method].call(this, context); 
koowa.js (line 445, col 17)

TODO: Move the config variables away from global space (generic variables) or it will no longer needed when we use the editor.js instead

**Comment by johanjanssens** [comment]
@jebbdomingo Is this a bug we should fix in koowa.js ?

**Comment by jebbdomingo** [comment]
@johanjanssens the undefined method call is fixed when I changed the function from "_action_default" to "_actionDefault" in nooku-ckeditor/resources/assets/js/editor.js but the "this.fireEvent" is not defined, probably conflicting with other javascript code.

**Comment by johanjanssens** [comment]
@jebbdomingo This could be or it could be a left over from a previous refactor. @ercanozkaya Can you have a look ?

**Comment by ercanozkaya** [comment]
Hi @jebbdomingo 
editor.js is better implemented using the event system rather than overriding the whole class. 

An example would be as follows:

```
$('.-koowa-form').on('koowa:validate', function() { console.log(arguments); });
```

You can copy this block into the function and return false if necessary: 
https://github.com/nooku/nooku-ckeditor/blob/develop/resources/assets/js/editor.js#L21-L33

**Comment by jebbdomingo** [comment]
thanks @ercanozkaya, noted on this. I'll get back to this.

**Comment by johanjanssens** [comment]
@jebbdomingo What is the status of this ?

**Comment by johanjanssens** [comment]
@jebbdomingo @ercanozkaya What is the state of this one? I rather not keep this open if we can fix it.

**Comment by jebbdomingo** [comment]
Unable to reproduce this issue, closing this ticket.
