### ISSUE TITLE
Set textarea value properly

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework-ckeditor#26]
We previously changed how to set the text in the textarea to `CKEDITOR.setData()`, see #23, that is to properly prefill the embed markup with javascript. Relying on it, however, will affect the scripts that post the form data to backend using javascript `$(".form").serialize()` see comment on TEXTman https://github.com/joomlatools/textman/pull/431#issuecomment-344878140 2nd item.

### Testing
Just make sure the `embed` plugin still works as expected and the TEXTman shared draft issue as described in item 2 of the comment https://github.com/joomlatools/textman/pull/431#issuecomment-344878140 is fixed.

**Comment by yiendos** [comment]
@jebbdomingo tested and looking good, save articles are now able to be shared and previewed
