### ISSUE TITLE
Semantic embed

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework-ckeditor#32]
Please describe the expected and actual behavior.
see https://github.com/joomlatools/textman/issues/186

**Comment by johanjanssens** [comment]
@jebbdomingo As part of this ticket we should also not forget to remove the other none semantic plugin from CkEditor.

**Comment by jebbdomingo** [comment]
@johanjanssens yes, sir. it's already removed https://github.com/joomlatools/joomlatools-framework-ckeditor/commit/c48ec2f59988acd166afd4df395f8c79fb6a973a

**Comment by johanjanssens** [comment]
Excellent.
