### ISSUE TITLE
Editor configurable via PHP

### ISSUE THREAD

**Issue by jebbdomingo** [joomlatools/joomlatools-framework-ckeditor#6]
Make the initialization of CKEditor be configurable on the fly via PHP instead of its JS config.

Example usage:

```
    <?= helper('editor.display', array(
        'name'    => 'text',
        'options' => array(
            'toolbar'          => 'Basic',
            'language'         => 'en',
            'contentsLanguage' => 'en'
        )
    )) ?>
```

**Comment by johanjanssens** [comment]
@jebbdomingo Could you add a little description to this ticket please to outline what you are trying to do ? This makes it easier to review your PR.
